/**
 * Orchestration Function: dynamic_softmax
 * Auto-generated by PTO ISA Compiler
 *
 * This code builds the task dependency graph using PTO Runtime.
 * Compile and run to generate task graph dump.
 */

#include "pto_runtime.h"
#include "pto_runtime.c"  // Include implementation for standalone build

/**
 * Build task graph for dynamic_softmax
 * Each CALL to an InCore function becomes a task with dependencies
 */
void dynamic_softmax_build_task_graph(PTORuntime* rt, float* input, float* output, float* temp_rowmax, float* temp_shifted, float* temp_exp, float* temp_rowsum) {
    // Task 0: rowmax
    int32_t t0 = pto_task_alloc(rt, "rowmax", NULL);
    pto_task_add_input(rt, t0, input, 0, 0, 8, 8);
    pto_task_add_output(rt, t0, temp_rowmax, 0, 0, 8, 1);
    pto_task_submit(rt, t0);

    // Task 1: rowexpandsub
    int32_t t1 = pto_task_alloc(rt, "rowexpandsub", NULL);
    pto_task_add_input(rt, t1, input, 0, 0, 8, 8);
    pto_task_add_input(rt, t1, temp_rowmax, 0, 0, 8, 1);
    pto_task_add_output(rt, t1, temp_shifted, 0, 0, 8, 8);
    pto_task_submit(rt, t1);

    // Task 2: elem_exp
    int32_t t2 = pto_task_alloc(rt, "elem_exp", NULL);
    pto_task_add_input(rt, t2, temp_shifted, 0, 0, 8, 8);
    pto_task_add_output(rt, t2, temp_exp, 0, 0, 8, 8);
    pto_task_submit(rt, t2);

    // Task 3: rowsum
    int32_t t3 = pto_task_alloc(rt, "rowsum", NULL);
    pto_task_add_input(rt, t3, temp_exp, 0, 0, 8, 8);
    pto_task_add_output(rt, t3, temp_rowsum, 0, 0, 8, 1);
    pto_task_submit(rt, t3);

    // Task 4: rowexpanddiv
    int32_t t4 = pto_task_alloc(rt, "rowexpanddiv", NULL);
    pto_task_add_input(rt, t4, temp_exp, 0, 0, 8, 8);
    pto_task_add_input(rt, t4, temp_rowsum, 0, 0, 8, 1);
    pto_task_add_output(rt, t4, output, 0, 0, 8, 8);
    pto_task_submit(rt, t4);

    // Task 5: rowmax
    int32_t t5 = pto_task_alloc(rt, "rowmax", NULL);
    pto_task_add_input(rt, t5, input, 0, 0, 8, 8);
    pto_task_add_output(rt, t5, temp_rowmax, 0, 0, 8, 1);
    pto_task_submit(rt, t5);

    // Task 6: rowexpandsub
    int32_t t6 = pto_task_alloc(rt, "rowexpandsub", NULL);
    pto_task_add_input(rt, t6, input, 0, 0, 8, 8);
    pto_task_add_input(rt, t6, temp_rowmax, 0, 0, 8, 1);
    pto_task_add_output(rt, t6, temp_shifted, 0, 0, 8, 8);
    pto_task_submit(rt, t6);

    // Task 7: elem_exp
    int32_t t7 = pto_task_alloc(rt, "elem_exp", NULL);
    pto_task_add_input(rt, t7, temp_shifted, 0, 0, 8, 8);
    pto_task_add_output(rt, t7, temp_exp, 0, 0, 8, 8);
    pto_task_submit(rt, t7);

    // Task 8: rowsum
    int32_t t8 = pto_task_alloc(rt, "rowsum", NULL);
    pto_task_add_input(rt, t8, temp_exp, 0, 0, 8, 8);
    pto_task_add_output(rt, t8, temp_rowsum, 0, 0, 8, 1);
    pto_task_submit(rt, t8);

    // Task 9: rowexpanddiv
    int32_t t9 = pto_task_alloc(rt, "rowexpanddiv", NULL);
    pto_task_add_input(rt, t9, temp_exp, 0, 0, 8, 8);
    pto_task_add_input(rt, t9, temp_rowsum, 0, 0, 8, 1);
    pto_task_add_output(rt, t9, output, 0, 0, 8, 8);
    pto_task_submit(rt, t9);

}

/**
 * Main: Build task graph and dump to file
 */
int main(int argc, char** argv) {
    PTORuntime rt;
    pto_runtime_init(&rt);

    // Declare buffers
    float input[64];
    float output[64];
    float temp_rowmax[8];
    float temp_shifted[64];
    float temp_exp[64];
    float temp_rowsum[8];

    // Build task graph
    dynamic_softmax_build_task_graph(&rt, input, output, temp_rowmax, temp_shifted, temp_exp, temp_rowsum);

    // Dump task graph
    printf("\n");
    pto_runtime_dump_stdout(&rt);
    pto_runtime_dump(&rt, "dynamic_softmax_task_graph.txt");

    pto_runtime_shutdown(&rt);
    return 0;
}